behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      use_recurrent: true
      sequence_length: 64
      memory_size: 1024
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 0.0003
        network_settings:
          hidden_units: 256
      gail:
        strength: 0.02
        gamma: 0.99
        demo_path: C:/Users/ybdto/OneDrive/Documents/unity/new_wmmc/WhoMovedMyCheese
          - Copy/Assets/Demonstrations/MazeRunner_1.demo
    behavioral_cloning:
      demo_path: C:/Users/ybdto/OneDrive/Documents/unity/new_wmmc/WhoMovedMyCheese
        - Copy/Assets/Demonstrations/MazeRunner_1.demo
      strength: 0.02
      steps: 50000
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 5000
